title: Mike Aspinall
logo: https://avatars.githubusercontent.com/u/171336216?s=400&u=f2b16aec84b361e2e924f091a458317eab63910e&v=4
description: Data Science student
#show_downloads: true
theme: jekyll-theme-minimal
